version: '3'

services:
        mongo:
                container_name: mongo
                image: mongo
                restart: always
                ports:
                        - "27017:27017"
        mongo-express:
                container_name: mongo-express
                image: mongo-express
                restart: always
                environment:
                        ME_CONFIG_MONGODB_SERVER: mongo
                ports:
                        - "8081:8081"
        postgres:
                container_name: postgres
                image: postgres
                restart: always
                environment:
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_USER: postgres
                ports:
                        - "5432:5432"
        pgadmin:
                container_name: pgadmin
                image: dpage/pgadmin4
                restart: always
                ports:
                        - "15432:80"
                environment:
                        PGADMIN_DEFAULT_EMAIL: pgadmin
                        PGADMIN_DEFAULT_PASSWORD: pgadmin
        elasticsearch:
                container_name: elasticsearch
                image: elasticsearch:7.5.1
                ports:
                        - "9200:9200"
                        - "9300:9300"
                environment:
                        discovery.type: single-node
        kibana:
                container_name: kibana
                image: kibana:7.5.1
                ports:
                        - "5601:5601"